name: Update an existing page
description: Report a bug or request more information about an existing page.
labels:
  - content-update
body:
  - type: markdown
    attributes:
      value: Does one of our existing page need an update? Let us know here!

  - type: input
    attributes:
      label: Which page needs an update?
      description: Link to the page that needs to be updated
    validations:
      required: true

  - type: textarea
    attributes:
      label: What needs to be updated?
      description: Please be as detailed as possible here. If you ran into a bug following a doc, the more information you can include, the bettter.
    validations:
      required: true
